name: FireSpawn
main: firespawn\Main
version: 1.0.0
api: [3.0.0-ALPHA7,3.0.0-ALPHA8,3.0.0-ALPHA9]
author: SkySeven

commands:
  hub:
    description: Go back to hub
  lobby:
    description: Go back to lobby
  spawn:
    description: Go back to spawn
  sethub:
    description: set the hub
  setspawn:
    description: set the spawn
